name: Auto Tag

on:
  push:
    branches:
      - main
      - master

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}  # This is crucial

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          NEW_TAG=$(echo $LATEST_TAG | awk -F. '{printf("v%d.%d.%d", $1, $2, $3+1)}')
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Create and push new tag
        if: steps.get_tag.outputs.latest_tag != steps.get_tag.outputs.new_tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a ${{ steps.get_tag.outputs.new_tag }} -m "Automated tag for commit $GITHUB_SHA"
          git push origin ${{ steps.get_tag.outputs.new_tag }}
